# -*- coding: utf-8 -*-
"""ProjectTFFile_With_CrossValdation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19mZU60uRewDaf3fEcVfxop_-ggxNfpu1

This is Ramkishore Rao's Project - Application of Tensor Flow and Keras for Loan Dataset
"""

# TENSOR FLOW/KERAS
# CROSS VALIDATION ONLY, NOT USED IN REPORT

import tensorflow.keras
from tensorflow . keras .models import Sequential
from tensorflow . keras . layers import Dense , Activation
from tensorflow . keras . callbacks import EarlyStopping
from sklearn . model_selection import train_test_split

import numpy as np
import pandas as pd
from sklearn import metrics
import sklearn
from sklearn.model_selection import train_test_split
import io
import requests
from sklearn.metrics import RocCurveDisplay
from sklearn.metrics import mean_squared_error
from sklearn.metrics import roc_curve, auc
import matplotlib.pyplot as plt
from sklearn.model_selection import StratifiedKFold

!pip install theano

df = pd.read_csv('/content/initialmodel2.csv', on_bad_lines="skip", engine="python")

df.head()
len(df)

df1 = df.pop('Defaulted')

df['Defaulted'] = df1

df.drop(['Unnamed: 0'] , axis = 1, inplace =True)

df = df.dropna()
print(df.head())

"""Split dataframe into X and y"""

df = df.iloc[0:20000]

X = df.iloc[:, :-1]

Y = df.iloc[:,-1].astype(int)

# Split into train and test

X_train, X_test, y_train, y_test = train_test_split(X, Y, random_state = 1, test_size = 0.2)

"""Split train into train1 and val1"""

X_train1, X_val1, y_train1, y_val1 = train_test_split(X_train, y_train, random_state = 1, test_size = 0.15)

X = X_train.to_numpy()
y = y_train.to_numpy()

len(X)

len(y)

KFold = StratifiedKFold(n_splits =5, shuffle = True)
cvscores = []

for train, test in KFold.split(X, y):
  model = Sequential()
  model.add(Dense(100, input_dim=X_train1.shape[1], activation='relu',
                  kernel_initializer='random_normal'))
  model.add(Dense(50,activation='relu',kernel_initializer='random_normal'))
  model.add(Dense(25,activation='relu',kernel_initializer='random_normal'))
  model.add(Dense(1,activation='sigmoid',kernel_initializer='random_normal'))
  model.compile(loss='binary_crossentropy', 
                optimizer=tensorflow.keras.optimizers.Adam(),
                metrics =['accuracy'])
  model.fit(X[train], y[train], epochs = 150, batch_size = 10, verbose = 0)
  scores = model.evaluate(X[test], y[test], verbose = 0)
  print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))
  cvscores.append(scores[1]*100)

print("%.2f%% (+/- %.2f%%)" % (np.mean(cvscores), np.std(cvscores)))

pred = model.predict(X_test)
pred

mse2 = mean_squared_error(pred, y_test, squared=False)

mse2

pred1 = np.round(pred) # this takes continues output and transforms to binary values of 0 and 1
pred1.shape

pred1 # this is the output target value array for the test dataset

from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import roc_auc_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score

accuracy1 = accuracy_score(y_test, pred1)
precision1 = precision_score(y_test, pred1)
recall1 = recall_score(y_test, pred1)
F1_score = f1_score(y_test, pred1)
confusion_mat_test = confusion_matrix(y_test, pred1)

confusion_mat_test

accuracy1

precision1

recall1

F1_score

auc= roc_auc_score(y_test, pred)

print(auc)

def plot_roc_curve(fper, tper):  
    plt.plot(fper, tper, color='orange', label='ROC')
    plt.plot([0, 1], [0, 1], color='darkblue', linestyle='--')
    plt.xlabel('False Positive Rate')
    plt.ylabel('True Positive Rate')
    plt.title('Receiver Operating Characteristic (ROC) Curve')
    plt.legend()
    plt.show()
    
probs = model.predict(X_test)
fper, tper, thresholds = roc_curve(y_test, probs) 
plot_roc_curve(fper, tper)

